version: '1'
services:
  - type: web
    name: agent-chat-frontend
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: BACKEND_URL
        value: your-backend-url-here